#!/usr/bin/env python
#Make sure that you have the requests package installed. Now, write a script that does the following:
##python using_third_party_package https://github.com/hsalluri259/scripts using_third
#   Accepts a URL and destination file name from the user calling the script.
#  Utilizes requests to make an HTTP request to the given URL.
#  Has an optional flag to state whether or not the response should be JSON or HTML (HTML by default).
#  Writes the contents of the page out to the destination.
#Note: You'll want to use the text attribute to get the HTML. To write this content on Python 2, you'll need to convert the unicode object to a string by using res.text.encode("UTF-8").
import sys
import requests
#from argparse import ArgumentParser
import argparse

parser = argparse.ArgumentParser(description='Write the pages out to the destination')

parser.add_argument('url', help='URL to store the contents of')
parser.add_argument('filename', help='the filename to store the content under')
parser.add_argument('--content-type', '-c',
                    default='html',
                    choices=['html,''json'],
                    help='the content-type of the URL being requested')

args = parser.parse_args()

res = requests.get(args.url)
if res.status_code >= 400:
    print("Error: code received: %s" % res.status_code)
    sys.exit(1)
if args.content_type == 'json':
    try:
        content = res.json()
    except valueError:
        print("Error: content is not json")
        sys.exit(1)
else:
    content = res.text
with open(args.filename, 'w') as f:
    f.write(content.encode("UTF-8"))
    print("Content written to '%s'" % args.filename)
